spring:
  datasource:
    url: jdbc:mysql://pi.com:3306/mybatis
    username: xiaokexiang
    password: 832231
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      connection-timeout: 3000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: io.spring.mybatis.config